### ISSUE TITLE
Unique selection 

### ISSUE THREAD

**Issue by afifoperantic** [azizali/react-super-treeview#13]
Hi,

I would like to know : 

*  if the unique selection option exists ie using radiobox instead of checkboxes

* If the onSelect event can be triggered when a child were selected

Thanks,

**Comment by azizali** [comment]
1. if the unique selection option exists ie using radiobox instead of checkboxes
No this does not exist right now.

2. If the onSelect event can be triggered when a child were selected
Whenever any node is checked/unchecked the `onCheckToggleCb` prop triggers.

The callback contains the node(s) which were checked/unchecked.

Here is the example:
http://azizali.com/react-super-treeview/examples/#checkbox
